<a href="https://colab.research.google.com/github/apanish-cell/Learning-DeepLearning/blob/main/Learning_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning DeepLearning

In [1]:
import torch
import numpy as np

In [7]:
# Lists
my_list = [[1,3,5,6],[1,3,5,6]]
my_list

[[1, 3, 5, 6], [1, 3, 5, 6]]

In [15]:
A = np.random.randn(3,3)
A.dtype

dtype('float64')

## Tensors

In [13]:
tensor = torch.randn(3,3,3,3)
tensor

tensor([[[[ 5.7819e-01, -1.0521e+00, -7.3733e-01],
          [-4.5947e-01,  1.0455e+00, -2.8680e-01],
          [-9.4472e-01,  2.3939e+00,  5.3496e-01]],

         [[-3.3418e-03, -1.8614e+00, -1.0533e+00],
          [-1.5225e+00, -2.4216e-01,  2.3510e+00],
          [ 8.9946e-02, -2.2142e+00, -6.0295e-01]],

         [[ 1.2947e-01,  7.6171e-01,  5.4646e-01],
          [-1.8751e+00,  1.0413e+00,  1.7284e+00],
          [-2.5116e+00, -5.5039e-02,  6.4919e-02]]],


        [[[-2.2554e-01, -2.1024e-01, -8.1339e-01],
          [-9.0107e-01, -1.2519e+00,  1.4941e+00],
          [ 6.9220e-04,  6.4884e-01,  5.2677e-02]],

         [[-4.1071e-01, -1.5804e+00, -2.9186e+00],
          [ 3.4396e-01, -1.1958e+00, -4.2088e-01],
          [ 2.9274e+00,  4.9059e-02,  2.3806e-02]],

         [[ 1.2991e+00,  9.0838e-02,  4.5123e-01],
          [-3.4397e+00, -1.1239e+00, -7.7133e-01],
          [-1.0947e+00, -1.9951e+00, -4.6872e-01]]],


        [[[ 1.6295e+00,  1.0791e+00,  2.7574e-01],
          [ 4.6

In [16]:
## Create tensor out of np array
myTensor = torch.tensor(A)
myTensor


tensor([[-0.0927, -0.8504, -0.1089],
        [ 0.9798, -0.4835, -0.3143],
        [ 0.1167,  1.3396,  0.5251]], dtype=torch.float64)

## Tensor Reshape and Slicing

In [18]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
# Reshape if we don't know number of items
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# Slices
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
for i in range(4):
  my_torch5[4] = 12+i
my_torch5

tensor([ 0,  1,  2,  3, 15,  5,  6,  7,  8,  9])

## Tensor Math

In [ ]:
tensor1 =
tensor2